### ISSUE TITLE
Online version only accessible for money?

### ISSUE THREAD

**Issue by ShalokShalom** [yousefvand/shellman-ebook#1]
![Screenshot_20210402_142552](https://user-images.githubusercontent.com/6344099/113415420-766fb100-93bf-11eb-83ba-30aa305a7b70.png)

https://leanpub.com/shellman/read_full

**Comment by yousefvand** [comment]
Hey. Until now I didn't know online version is not available for unpublished books. BTW, even if you choose to buy, since there's nothing to buy you can't go with online option. Unfortunately only the rest of links are working and I'll remove the online option. Thanks for heads up.
